//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bumbo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bumbo.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal bezoekers.
        /// </summary>
        internal static string AantalBezoekers {
            get {
                return ResourceManager.GetString("AantalBezoekers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal vulkarren.
        /// </summary>
        internal static string AantalVulkarren {
            get {
                return ResourceManager.GetString("AantalVulkarren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acties.
        /// </summary>
        internal static string Acties {
            get {
                return ResourceManager.GetString("Acties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuleren.
        /// </summary>
        internal static string Annuleren {
            get {
                return ResourceManager.GetString("Annuleren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevestig template.
        /// </summary>
        internal static string Bevestig {
            get {
                return ResourceManager.GetString("Bevestig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coli uitladen.
        /// </summary>
        internal static string Coli_uitladen {
            get {
                return ResourceManager.GetString("Coli uitladen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collis.
        /// </summary>
        internal static string CollisLabel {
            get {
                return ResourceManager.GetString("CollisLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Beheren.
        /// </summary>
        internal static string DataNAV {
            get {
                return ResourceManager.GetString("DataNAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string Datum {
            get {
                return ResourceManager.GetString("Datum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Di.
        /// </summary>
        internal static string Di {
            get {
                return ResourceManager.GetString("Di", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinsdag.
        /// </summary>
        internal static string Dinsdag {
            get {
                return ResourceManager.GetString("Dinsdag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        internal static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donderdag.
        /// </summary>
        internal static string Donderdag {
            get {
                return ResourceManager.GetString("Donderdag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duits.
        /// </summary>
        internal static string Duits {
            get {
                return ResourceManager.GetString("Duits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engels.
        /// </summary>
        internal static string Engels {
            get {
                return ResourceManager.GetString("Engels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen normeringen beschikbaar..
        /// </summary>
        internal static string GeenNormeringenBeschikbaar {
            get {
                return ResourceManager.GetString("GeenNormeringenBeschikbaar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen templates beschikbaar..
        /// </summary>
        internal static string GeenTemplatesBeschikbaar {
            get {
                return ResourceManager.GetString("GeenTemplatesBeschikbaar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kassa .
        /// </summary>
        internal static string Kassa {
            get {
                return ResourceManager.GetString("Kassa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klanten.
        /// </summary>
        internal static string KlantenLabel {
            get {
                return ResourceManager.GetString("KlantenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma.
        /// </summary>
        internal static string Ma {
            get {
                return ResourceManager.GetString("Ma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maak.
        /// </summary>
        internal static string Maak {
            get {
                return ResourceManager.GetString("Maak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maak nieuwe template.
        /// </summary>
        internal static string MaakNieuweTemplate {
            get {
                return ResourceManager.GetString("MaakNieuweTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maandag.
        /// </summary>
        internal static string Maandag {
            get {
                return ResourceManager.GetString("Maandag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        internal static string Naam {
            get {
                return ResourceManager.GetString("Naam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nederlands.
        /// </summary>
        internal static string Nederlands {
            get {
                return ResourceManager.GetString("Nederlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normeringen.
        /// </summary>
        internal static string NormeringenTitle {
            get {
                return ResourceManager.GetString("NormeringenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normering.
        /// </summary>
        internal static string NormeringNAV {
            get {
                return ResourceManager.GetString("NormeringNAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opslaan.
        /// </summary>
        internal static string OpslaanButton {
            get {
                return ResourceManager.GetString("OpslaanButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maak Prognose.
        /// </summary>
        internal static string PrognoseNAV {
            get {
                return ResourceManager.GetString("PrognoseNAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prognose voor benodigde bezetting wordt volgens de volgende richtlijnen berekend:.
        /// </summary>
        internal static string PrognoseText {
            get {
                return ResourceManager.GetString("PrognoseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schatting Templates.
        /// </summary>
        internal static string SchattingTemplatesTitle {
            get {
                return ResourceManager.GetString("SchattingTemplatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speciale feestdagen.
        /// </summary>
        internal static string SpecialeFeestdagen {
            get {
                return ResourceManager.GetString("SpecialeFeestdagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiegelen.
        /// </summary>
        internal static string Spiegelen {
            get {
                return ResourceManager.GetString("Spiegelen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template .
        /// </summary>
        internal static string TemplatePagina {
            get {
                return ResourceManager.GetString("TemplatePagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        internal static string TitelLabel {
            get {
                return ResourceManager.GetString("TitelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitloggen.
        /// </summary>
        internal static string Uitloggen {
            get {
                return ResourceManager.GetString("Uitloggen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uren.
        /// </summary>
        internal static string Uren {
            get {
                return ResourceManager.GetString("Uren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vers .
        /// </summary>
        internal static string Vers {
            get {
                return ResourceManager.GetString("Vers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vr.
        /// </summary>
        internal static string Vr {
            get {
                return ResourceManager.GetString("Vr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijdag.
        /// </summary>
        internal static string Vrijdag {
            get {
                return ResourceManager.GetString("Vrijdag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulploeg .
        /// </summary>
        internal static string Vulploeg {
            get {
                return ResourceManager.GetString("Vulploeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzigen.
        /// </summary>
        internal static string Wijzigen {
            get {
                return ResourceManager.GetString("Wijzigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wo.
        /// </summary>
        internal static string Wo {
            get {
                return ResourceManager.GetString("Wo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woensdag.
        /// </summary>
        internal static string Woensdag {
            get {
                return ResourceManager.GetString("Woensdag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za.
        /// </summary>
        internal static string Za {
            get {
                return ResourceManager.GetString("Za", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaterdag.
        /// </summary>
        internal static string Zaterdag {
            get {
                return ResourceManager.GetString("Zaterdag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zo.
        /// </summary>
        internal static string Zo {
            get {
                return ResourceManager.GetString("Zo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zondag.
        /// </summary>
        internal static string Zondag {
            get {
                return ResourceManager.GetString("Zondag", resourceCulture);
            }
        }
    }
}
